server:
  port: 7003

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

services:
  connection:
    retryBackoff:
      maxSeconds: 5

auth:
  anonymous:
    enabled: false
  getAll:
    enabled: false
