server:
  port: 7003

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

okHttpClient:
  retries:
    maxElapsedBackoffMs: 5000

# For options, see com.netflix.spinnaker.fiat.config.FiatServerConfigurationProperties

logging:
  config: classpath:logback-defaults.xml
