server:
  port: 7003

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

okHttpClient:
  retries:
    maxElapsedBackoffMs: 5000

endpoints:
  health:
    sensitive: false

auth:
  anonymous:
    enabled: false
  getAll:
    enabled: false
  userSync:
    intervalMs: 600000
    retryInterval: 10000
