FROM alpine:3.11
LABEL maintainer="sig-platform@spinnaker.io"
COPY fiat-web/build/install/fiat /opt/fiat
RUN apk --no-cache add --update bash openjdk11-jre
RUN addgroup -S -g 10111 spinnaker
RUN adduser -S -G spinnaker -u 10111 spinnaker
RUN mkdir -p /opt/fiat/plugins && chown -R spinnaker:nogroup /opt/fiat/plugins
USER spinnaker
CMD ["/opt/fiat/bin/fiat"]
