name: Bump Dependencies

on:
  repository_dispatch:
    types: [bump-dependencies]

jobs:
  bump-dependencies:
    if: startsWith(github.repository, 'spinnaker/')
    runs-on: ubuntu-latest
    steps:
    - uses: spinnaker/bumpdeps@master
      with:
        ref: ${{ github.event.client_payload.ref }}
        baseBranch: ${{ github.event.client_payload.branch }}
        key: fiatVersion
<<<<<<< HEAD
        repositories: clouddriver,echo,front50,gate,halyard,igor,keel,orca
=======
        repositories: clouddriver,echo,front50,gate,igor,keel,orca
        mavenRepositoryUrl: https://repo.maven.apache.org/maven2
        groupId: io.spinnaker.fiat
        artifactId: fiat-bom
>>>>>>> 3cf7254 (chore(dependencies): don't create an autobump PR for halyard on a fia… (#938))
      env:
        GITHUB_OAUTH: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}
